# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import project_control_pb2 as project__control__pb2


class ProjectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsUserInProject = channel.unary_unary(
                '/greet.ProjectService/IsUserInProject',
                request_serializer=project__control__pb2.ProjectRequest.SerializeToString,
                response_deserializer=project__control__pb2.IsUserInProjectReply.FromString,
                )
        self.SendNotification = channel.unary_unary(
                '/greet.ProjectService/SendNotification',
                request_serializer=project__control__pb2.CreateNotificationRequest.SerializeToString,
                response_deserializer=project__control__pb2.NotificationReply.FromString,
                )


class ProjectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IsUserInProject(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsUserInProject': grpc.unary_unary_rpc_method_handler(
                    servicer.IsUserInProject,
                    request_deserializer=project__control__pb2.ProjectRequest.FromString,
                    response_serializer=project__control__pb2.IsUserInProjectReply.SerializeToString,
            ),
            'SendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotification,
                    request_deserializer=project__control__pb2.CreateNotificationRequest.FromString,
                    response_serializer=project__control__pb2.NotificationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.ProjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProjectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IsUserInProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.ProjectService/IsUserInProject',
            project__control__pb2.ProjectRequest.SerializeToString,
            project__control__pb2.IsUserInProjectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.ProjectService/SendNotification',
            project__control__pb2.CreateNotificationRequest.SerializeToString,
            project__control__pb2.NotificationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
