# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15project_control.proto\x12\x05greet\"5\n\x0eProjectRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"&\n\x14IsUserInProjectReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\"c\n\x19\x43reateNotificationRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\x0f\n\x07type_id\x18\x02 \x01(\x05\x12\x12\n\ncontent_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"\x1f\n\x11NotificationReply\x12\n\n\x02id\x18\x01 \x01(\t2\xa7\x01\n\x0eProjectService\x12\x45\n\x0fIsUserInProject\x12\x15.greet.ProjectRequest\x1a\x1b.greet.IsUserInProjectReply\x12N\n\x10SendNotification\x12 .greet.CreateNotificationRequest\x1a\x18.greet.NotificationReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project_control_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROJECTREQUEST']._serialized_start=32
  _globals['_PROJECTREQUEST']._serialized_end=85
  _globals['_ISUSERINPROJECTREPLY']._serialized_start=87
  _globals['_ISUSERINPROJECTREPLY']._serialized_end=125
  _globals['_CREATENOTIFICATIONREQUEST']._serialized_start=127
  _globals['_CREATENOTIFICATIONREQUEST']._serialized_end=226
  _globals['_NOTIFICATIONREPLY']._serialized_start=228
  _globals['_NOTIFICATIONREPLY']._serialized_end=259
  _globals['_PROJECTSERVICE']._serialized_start=262
  _globals['_PROJECTSERVICE']._serialized_end=429
# @@protoc_insertion_point(module_scope)
