"""update field

Revision ID: 4ecb0c0a06e1
Revises: 8dc795cf0f3c
Create Date: 2023-11-24 21:27:36.167134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecb0c0a06e1'
down_revision: Union[str, None] = '8dc795cf0f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_column('project_users', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('project_users', 'user_id')
    # ### end Alembic commands ###
