from enum import Enum


class Permission(Enum):
    GET_PROJECT = "GET_PROJECT"
    CREATE_PROJECT = "CREATE_PROJECT"
    UPDATE_PROJECT = "UPDATE_PROJECT"
    DELETE_PROJECT = "DELETE_PROJECT"

    GET_NOTIFICATION = "GET_NOTIFICATION"
    DELETE_NOTIFICATION = "DELETE_NOTIFICATION"
    MAKE_INVITE_LINK = "MAKE_INVITE_LINK"
    GET_INVITE_LINK = "GET_INVITE_LINK"
    DELETE_INVITE_LINK = "DELETE_INVITE_LINK"
    ACCEPT_INVITE_LINK = "ACCEPT_INVITE_LINK"
